#!/bin/bash
cd /home/ec2-user/ruby-on-rails
curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
echo 'eval "$(rbenv init -)"' >> ~/.bashrc
source ~/.bashrc
type rbenv
rbenv install 3.1.3
rbenv local 3.1.3
gem install -N rails 7.0.4
bundle install