#!/bin/bash

cd /home/ec2-user/ruby-on-rails
# If keyserver is unreachable, import keys directly from rvm.io
if ! gpg2 --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB ; then
    curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
    curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
fi
curl -sSL https://get.rvm.io | bash -s 1.29.10
source /home/../usr/local/rvm/scripts/rvm
rvm requirements
rvm install 3.1.3
yum -y install ruby-devel-3.1.3 gcc-7.3.1 zlib-devel-1.2.7 patch-2.7.1 gcc-c++-7.3.1
gem install -N rails -v 7.0.4
bundle install
